In [5]:
import numpy as np

In [2]:
hello_string = "hello World!"

In [3]:
# subsetting
hello_string[0]
#hello_string[-1]

'h'

In [4]:
# slicing
hello_string[:4]

'hell'

In [5]:
fruit_basket = ["orange", "apple", "melon", "cherry", "pear", "lemon"]

In [6]:
# subsetting
fruit_basket[1]

'apple'

In [7]:
# slicing
fruit_basket[:2]

['orange', 'apple']

In [6]:
one_d_array = np.array([1, 2, 3, 4, 5, 6])

In [7]:
one_d_array.shape

(6,)

In [16]:
two_d_array = np.array([[10, 2, 3.5, 4, 1, 6], [1.25, 2.3, 4, 1.8, 2.25, 3.45], [10, 5, 15, 25, 20, 30]])

In [13]:
two_d_array.shape

(3, 6)

In [14]:
three_d_array = np.array(
    [[[1, 2], [3, 4], [3, 4]], [[5, 6], [7, 8], [7, 8]], [[5, 6], [7, 8], [7, 8]], [[5, 6], [7, 8], [7, 8]]])


In [46]:
three_d_array.shape

(4, 3, 2)

In [14]:
print(one_d_array[0])
one_d_array[0:3]



1


array([1, 2, 3])

In [21]:
#two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
#two_d_array[1, 0]
two_d_array[:, :2]
#two_d_array[1, 0:2]

array([[1, 2],
       [4, 5]])

In [28]:
three_d_array = np.array(
     [[[1, 2], [3, 4], [3, 4]], [[5, 6], [7, 8], [7, 8]], [[5, 6], [7, 8], [7, 8]], [[5, 6], [7, 8], [7, 8]]])
three_d_array[:, 0:2, 0]

array([[1, 3],
       [5, 7],
       [5, 7],
       [5, 7]])

In [64]:
two_d_height = two_d_array[:, 0]
print(two_d_height)
two_d_height.mean()


[1 4]


2.5

In [23]:
a = np.array( [4, 2, 2, 1, 3] )

In [24]:
a = np.sort( a )


In [66]:
two_d_weight = two_d_array[:, 1]
two_d_weight.mean()


3.5