In [2]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [11]:
import numpy as np

two_d_array = np.array([[10, 2, 3.5, 4, 1, 5], [1.25, 2.3, 4, 1.8, 2.25, 3.45], [10, 5, 15, 25, 20, 30]])

weight_list = two_d_array[0]
print(weight_list)

[10.   2.   3.5  4.   1.   5. ]


In [9]:
import numpy as np
#Given, there are 5 numbers in the data set: (8, 12, 16, 24, 4). 
#What will be the sum of deviations of individual data points from their mean ?

data_set = np.array([8, 12, 16, 24, 4])
np.sum(data_set - np.mean(data_set))


-3.552713678800501e-15

In [8]:
import numpy as np
# If some outliers are introduced to the dataset, what will happen to the Standard Deviation ? 
# A) Standard Deviation is robust to outliers 
# B) Standard Deviation will increase with the introduction of outliers. 
# C) Standard Deviation will decrease with the introduction of outliers. 
# D) Can not be determined.

# B), SD will increase. As SD is the measure of dispersion of a set of data from its mean.
a_set = np.array([4, 5, 3, 4, 4])
print(np.std(a_set))
another_set = np.array([4, 5, 3, 4, 17])
np.std(another_set)


0.6324555320336759


5.238320341483518

In [ ]:
# Suppose the below positively skewed distribution has a median of 30, which of the following statement is true?
# A) Mean is greater than 30
# B) Mean is less than 30
# C) Mode is greater than 30
# D) Mode is less than 30
# E) Both A and D
# F) Both B and C

# By definition, the mean will be greater than the median, therefore A) is true. We do not have enough information to 
# comment on the mode except from the picture where it is shows the mode to be less than the median. So E) is the answer.

In [1]:
import numpy as np
# Which value can be the possible value for the median of the below distribution?
# A) 40
# B) 26
# C) 16
# D) 50

find_median = np.array([36, 54, 69, 82, 55, 43, 25, 22, 17])
new_find_median = np.cumsum(find_median)
new_find_median
median = (find_median.sum()/2)
print(median)
print(new_find_median)

201.5
[ 36  90 159 241 296 339 364 386 403]


In [6]:
fin_median = np.array([36, 54, 69, 82, 55, 43, 25, 22, 17])
np.median(fin_median)

43.0